title: Jonas Rieger
author:
  name: Jonas Rieger
  email: rieger@statistik.tu-dortmund.de
description: Personal webpage of Jonas Rieger

theme: minima

minima:
  date_format: "%Y-%m-%d"
  skin: dark
  social_links:
    twitter: Rieger94
    github: JonasRieger
    instagram: riegerjonas

include:
    - _pages
