title: Jonas Rieger
author:
  name: Jonas Rieger
  email: rieger@statistik.tu-dortmund.de
description: Personal webpage of Jonas Rieger

plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  date_format: "%Y-%m-%d"
  skin: dark
  social_links:
    twitter: Rieger94
    github: JonasRieger
    instagram: riegerjonas
    orcid: 0000-0002-0007-4478
    researchgate: Jonas-Rieger

include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    
