title: Jonas Rieger
author:
  name: Jonas Rieger
  email: rieger@statistik.tu-dortmund.de
description: Personal webpage of Jonas Rieger

plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima@41b97699af658128fa9983e5312ca5516641f335

minima:
  date_format: "%Y-%m-%d"
  skin: dark
  social_links:
    twitter: Rieger94
    mastodon:
     - username: rieger
       instance: ruhr.social
    github: JonasRieger
    instagram: riegerjonas
    orcid: 0000-0002-0007-4478
    researchgate: Jonas-Rieger
    huggingface: riegerjonas
    
include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    
