title: Jonas Rieger
author:
  name: Jonas Rieger
  email: rieger@statistik.tu-dortmund.de
description: Personal webpage of Jonas Rieger

plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

minima:
  date_format: "%Y-%m-%d"
minima:
  skin: dark
minima:
  social_links:
    twitter: Rieger94
    github: JonasRieger
    instagram: riegerjonas

include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock
    
